spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345678
    username: root
    url: 'jdbc:mysql://localhost:3306/fornecedor'
  jpa:
    hibernate:
      ddl-auto: update
